#!/bin/bash
# usb-automount.sh — Make plugged-in USB flash drives visible to the kiosk.
#
# The problem this solves:
#   The kiosk runs a bare X session (Openbox + Chrome, no desktop environment),
#   so there is no udisks2/gvfs agent and NOTHING mounts a flash drive when it
#   is plugged in. Chrome's file picker can only browse MOUNTED filesystems, so
#   the dashboard's "Offline Update" file dialog showed no USB stick at all and
#   staff could not select the release zip — the drive was detected by the
#   kernel, just never given a path.
#
#   This installs a udev rule that mounts any USB filesystem at /media/<dev>
#   the instant it appears. No extra packages (so it works on no-internet
#   kiosks), and it does not depend on X running — the Ctrl+Alt+F2 console
#   flow and usb-update.sh benefit too.
#
# Mounts are READ-ONLY on purpose: staff pull sticks without unmounting, and
# read-only makes that harmless. It also matches how usb-update.sh mounts (-o ro).
#
# Run once as root:   sudo bash /opt/kiosk-manager/usb-automount.sh
# Undo:               sudo bash /opt/kiosk-manager/usb-automount.sh --uninstall
# install.sh runs this automatically on a fresh install.

set -u

RULE_FILE="/etc/udev/rules.d/99-kiosk-usb-automount.rules"

# Writing under /etc needs root, but the kiosk user has passwordless sudo for
# tee (see install.sh), so this also works unattended from update.sh without a
# root login.
if [ "$(id -u)" = "0" ]; then SUDO=""; else SUDO="sudo -n"; fi

if [ "${1:-}" = "--uninstall" ]; then
    $SUDO rm -f "$RULE_FILE" 2>/dev/null || true
    $SUDO udevadm control --reload-rules 2>/dev/null || true
    echo "[OK] USB auto-mount rule removed ($RULE_FILE)"
    exit 0
fi

# udev RUN needs absolute paths — the rule file is not evaluated in a shell.
MOUNT_BIN="$(command -v systemd-mount 2>/dev/null || true)"
UMOUNT_BIN="$(command -v systemd-umount 2>/dev/null || true)"
if [ -z "$MOUNT_BIN" ] || [ -z "$UMOUNT_BIN" ]; then
    echo "[!] systemd-mount/systemd-umount not found — cannot install auto-mount." >&2
    echo "    Offline updates still work from a console:" >&2
    echo "      bash /opt/kiosk-manager/usb-update.sh" >&2
    exit 1
fi

$SUDO mkdir -p /media 2>/dev/null || true

# --no-block: udev kills RUN programs that linger, so never wait on the mount.
# --collect:  garbage-collect the unit if the mount fails or the stick is yanked.
# ID_FS_USAGE=="filesystem" matches partitions AND partitionless ("superfloppy")
# sticks, while skipping the whole-disk node of a partitioned drive.
RULE=$(cat <<EOF
# Kiosk Manager — auto-mount USB flash drives so the dashboard's Offline Update
# file picker can see them. Auto-generated by usb-automount.sh; do not edit.
ACTION=="add", SUBSYSTEM=="block", KERNEL=="sd*", ENV{ID_BUS}=="usb", ENV{ID_FS_USAGE}=="filesystem", RUN{program}+="$MOUNT_BIN --no-block --collect -o ro \$devnode /media/%k"
ACTION=="remove", SUBSYSTEM=="block", KERNEL=="sd*", ENV{ID_BUS}=="usb", RUN{program}+="$UMOUNT_BIN /media/%k"
EOF
)

if ! printf '%s\n' "$RULE" | $SUDO tee "$RULE_FILE" >/dev/null 2>&1; then
    echo "[!] Could not write $RULE_FILE." >&2
    echo "    Passwordless sudo for tee is missing (older install). Run once as root:" >&2
    echo "      sudo bash $0" >&2
    exit 1
fi
$SUDO chmod 644 "$RULE_FILE" 2>/dev/null || true

# udevd watches /etc/udev/rules.d, but ask for a reload anyway and re-trigger
# USB block devices so a stick that is already plugged in mounts right now.
if $SUDO udevadm control --reload-rules 2>/dev/null; then
    $SUDO udevadm trigger --subsystem-match=block --property-match=ID_BUS=usb \
        --action=add 2>/dev/null || true
else
    echo "[i] Could not run udevadm (needs root). The rule is installed and"
    echo "    takes effect on the next reboot, or immediately after:"
    echo "      sudo udevadm control --reload-rules"
fi

echo "[OK] USB auto-mount installed ($RULE_FILE)"
echo "     Flash drives now mount read-only under /media/ as soon as they are"
echo "     plugged in, and appear in the Offline Update file picker."
