#!/bin/bash
# usb-automount.sh — Make plugged-in USB flash drives visible to the kiosk.
#
# The problem this solves:
#   The kiosk runs a bare X session (Openbox + Chrome, no desktop environment),
#   so there is no udisks2/gvfs agent and NOTHING mounts a flash drive when it
#   is plugged in. Chrome's file picker can only browse MOUNTED filesystems, so
#   the dashboard's "Offline Update" file dialog showed no USB stick at all and
#   staff could not select the release zip — the drive was detected by the
#   kernel, just never given a path.
#
#   This installs a udev rule that mounts any USB filesystem at /media/<dev>
#   the instant it appears. No extra packages (so it works on no-internet
#   kiosks), and it does not depend on X running — the Ctrl+Alt+F2 console
#   flow and usb-update.sh benefit too.
#
# Mounts are READ-ONLY on purpose: staff pull sticks without unmounting, and
# read-only makes that harmless. It also matches how usb-update.sh mounts (-o ro).
#
# Run once as root:   sudo bash /opt/kiosk-manager/usb-automount.sh
# Undo:               sudo bash /opt/kiosk-manager/usb-automount.sh --uninstall
# install.sh runs this automatically on a fresh install.

set -u

RULE_FILE="/etc/udev/rules.d/99-kiosk-usb-automount.rules"

if [ "$(id -u)" != "0" ]; then
    echo "[!] This must run as root:  sudo bash $0" >&2
    exit 1
fi

if [ "${1:-}" = "--uninstall" ]; then
    rm -f "$RULE_FILE"
    udevadm control --reload-rules 2>/dev/null || true
    echo "[OK] USB auto-mount rule removed ($RULE_FILE)"
    exit 0
fi

# udev RUN needs absolute paths — the rule file is not evaluated in a shell.
MOUNT_BIN="$(command -v systemd-mount 2>/dev/null || true)"
UMOUNT_BIN="$(command -v systemd-umount 2>/dev/null || true)"
if [ -z "$MOUNT_BIN" ] || [ -z "$UMOUNT_BIN" ]; then
    echo "[!] systemd-mount/systemd-umount not found — cannot install auto-mount." >&2
    echo "    Offline updates still work from a console:" >&2
    echo "      bash /opt/kiosk-manager/usb-update.sh" >&2
    exit 1
fi

mkdir -p /media

# --no-block: udev kills RUN programs that linger, so never wait on the mount.
# --collect:  garbage-collect the unit if the mount fails or the stick is yanked.
# ID_FS_USAGE=="filesystem" matches partitions AND partitionless ("superfloppy")
# sticks, while skipping the whole-disk node of a partitioned drive.
cat > "$RULE_FILE" <<EOF
# Kiosk Manager — auto-mount USB flash drives so the dashboard's Offline Update
# file picker can see them. Auto-generated by usb-automount.sh; do not edit.
ACTION=="add", SUBSYSTEM=="block", KERNEL=="sd*", ENV{ID_BUS}=="usb", ENV{ID_FS_USAGE}=="filesystem", RUN{program}+="$MOUNT_BIN --no-block --collect -o ro \$devnode /media/%k"
ACTION=="remove", SUBSYSTEM=="block", KERNEL=="sd*", ENV{ID_BUS}=="usb", RUN{program}+="$UMOUNT_BIN /media/%k"
EOF
chmod 644 "$RULE_FILE"

udevadm control --reload-rules 2>/dev/null || true
# Re-trigger USB block devices only, so a stick already plugged in mounts now.
udevadm trigger --subsystem-match=block --property-match=ID_BUS=usb --action=add 2>/dev/null || true

echo "[OK] USB auto-mount installed ($RULE_FILE)"
echo "     Flash drives now mount read-only under /media/ as soon as they are"
echo "     plugged in, and appear in the Offline Update file picker."
